### ISSUE TITLE
Hostname hardcoded

### ISSUE THREAD

**Issue by martic** [LebToki/Laragon-Dashboard#19]
I use .test as my local domain.

Can you get the configured domain from the Preferences:

![image](https://github.com/LebToki/Laragon-Dashboard/assets/633920/1d0e9ea4-7338-463a-b16d-a57a2bf55f48)

**Comment by LebToki** [comment]
Hi,

did it not automatically detect .test at your end ?

very strange 
open index.php and replace all instances of .local to .test
and I'll check why it didn't detect it automatically !

Can I ask you a question : 
Are your domains listing ?
if so then check Line 218 and 219 to see if your Laragon installation is installed in a different location and if you need a customized version then please let me know!

Thanks for reporting it

**Comment by martic** [comment]
it did not, its hard coded in the code.
so I added a variable.
```
$ignored = array('favicon_io');
$folders = array_filter(glob('*'), 'is_dir');
$local_domain = ".test";
```
and replaced the '.local' with $local_domain
like this
```
htmlspecialchars($host) . $local_domain . '/user"
```

**Comment by LebToki** [comment]
$admin.link --> lines 951, 956, 961, 971, 976, 941 and 992 should be changed too to .test to have this all done for you smoothly
until i release another version by the weekend to test why it didn't automatically detect your .test

**Comment by martic** [comment]
thanks. Also check the email page that's also go a D: drive hard link

**Comment by LebToki** [comment]
for open_email.php
inside /assets/inbox/

I can think for this for now:
<?php
    // Define potential paths
    $emailFilePaths = [
        'C:/laragon/bin/sendmail/output/',
        'D:/laragon/bin/sendmail/output/'
    ];

    function findEmailFile($filename, $paths) {
        foreach ($paths as $path) {
            $filePath = rtrim($path, '/') . '/' . basename($filename);
            if (file_exists($filePath)) {
                return $filePath;
            }
        }
        return false;
    }

    if (isset($_GET['email'])) {
        $emailFile = findEmailFile($_GET['email'], $emailFilePaths);
        if ($emailFile) {
            $content = file_get_contents($emailFile);
            if ($content === false) {
                echo "Error reading email file.";
            } else {
                // Decode and display content as HTML
                $decodedContent = htmlspecialchars_decode($content, ENT_QUOTES);
                echo nl2br($decodedContent);
            }
        } else {
            echo "Email not found.";
        }
    } else {
        echo "No email specified.";
    }
?>

**Comment by LebToki** [comment]
Changes pushed for version 2.3.5 thanks for the report!

**Comment by LebToki** [comment]
Issue closed for now !
Thanks again @martic
